services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ibbi_user
      POSTGRES_PASSWORD: ibbi_password
      POSTGRES_DB: ibbi_db
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
