version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ibbi_user
      POSTGRES_PASSWORD: ibbi_password
      POSTGRES_DB: ibbi_db
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  backend:
    build: ./backend
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
  angular:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
